#include "nsISupports.idl"

[scriptable, uuid(57cf94b5-2449-11dc-8314-0800200c9a66)]
interface nsIColdFire : nsISupports
{
	attribute boolean requestHeaderEnabled;
	attribute string extensionVersion;
	
	
	void addVariable(in string variable);
	void removeVariable(in unsigned long index);
	void getVariables(out unsigned long count, [array, size_is(count), retval] out string retv);
	void clearVariables();
	
};

